name: Windows Build with LLVM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Download pre-built LLVM
        run: |
          # Download pre-built LLVM 17 (more stable than 18)
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/LLVM-17.0.6-win64.exe" -OutFile "llvm.exe"
          
          # Extract LLVM silently to C:\LLVM
          Start-Process -FilePath "llvm.exe" -ArgumentList "/S", "/D=C:\LLVM" -Wait -NoNewWindow
          
          # Verify installation
          if (Test-Path "C:\LLVM\bin\clang.exe") {
            Write-Host "LLVM installed successfully"
            echo "C:\LLVM\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
            
            # Check what's actually installed
            Write-Host "LLVM installation contents:"
            Get-ChildItem "C:\LLVM" -Directory | ForEach-Object { Write-Host "  Directory: $_" }
            
            # Check for libclang
            if (Test-Path "C:\LLVM\bin\libclang.dll") {
              Write-Host "Found libclang.dll in C:\LLVM\bin"
            }
            if (Test-Path "C:\LLVM\lib\libclang.lib") {
              Write-Host "Found libclang.lib in C:\LLVM\lib"
            }
            
            # Check for CMake files
            if (Test-Path "C:\LLVM\lib\cmake") {
              Write-Host "Found CMake directory"
              Get-ChildItem "C:\LLVM\lib\cmake" -Directory | ForEach-Object { Write-Host "  CMake module: $_" }
            } else {
              Write-Host "No CMake directory found - will use direct library linking"
            }
          } else {
            Write-Error "LLVM installation failed"
            exit 1
          }
          
      - name: Configure CMake
        run: |
          # Try with CMake config if available, otherwise use direct paths
          $llvmArgs = @()
          if (Test-Path "C:\LLVM\lib\cmake\llvm") {
            $llvmArgs += "-DLLVM_DIR=C:\LLVM\lib\cmake\llvm"
            $llvmArgs += "-DClang_DIR=C:\LLVM\lib\cmake\clang"
          } else {
            Write-Host "Using direct library paths since CMake config not found"
            $llvmArgs += "-DLIBCLANG_LIBRARY=C:\LLVM\lib\libclang.lib"
            $llvmArgs += "-DLIBCLANG_INCLUDE_DIR=C:\LLVM\include"
          }
          
          cmake -B build -S . `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            $llvmArgs
            
      - name: Build
        run: cmake --build build --config Release --verbose
        
      - name: List build output
        run: |
          Get-ChildItem -Path build\bin\Release -Recurse
          
      - name: Package Windows Release
        run: |
          New-Item -ItemType Directory -Force -Path release-windows
          
          # Use the comprehensive DLL bundling script
          if (Test-Path "scripts\bundle-windows-deps.ps1") {
            Write-Host "Using comprehensive DLL bundling script"
            .\scripts\bundle-windows-deps.ps1 `
              -ExePath "build\bin\Release\codemap.exe" `
              -OutputDir "release-windows" `
              -LLVMPath "C:\LLVM" `
              -VerboseOutput
          } else {
            Write-Host "Bundling script not found, using fallback method"
            # Fallback: Copy executable
            Copy-Item build\bin\Release\codemap.exe release-windows\
            
            # Copy required DLLs from LLVM
            $llvmDlls = @(
              "libclang.dll",
              "LLVM-C.dll",
              "LLVM-17.dll",
              "LLVM.dll"
            )
            
            foreach ($dll in $llvmDlls) {
              $dllPath = "C:\LLVM\bin\$dll"
              if (Test-Path $dllPath) {
                Copy-Item $dllPath release-windows\
                Write-Host "Copied: $dll"
              } else {
                Write-Host "Not found: $dll (may be optional)"
              }
            }
          }
          
          # Copy frontend and docs
          Copy-Item -Recurse frontend release-windows\
          Copy-Item README.md release-windows\
          
          # List package contents
          Write-Host "Package contents:"
          Get-ChildItem -Path release-windows -Recurse | Format-Table Mode, LastWriteTime, Length, Name
          
          # Verify critical DLLs are present
          $criticalDlls = @("libclang.dll")
          $missingCritical = @()
          foreach ($dll in $criticalDlls) {
            if (!(Test-Path "release-windows\$dll")) {
              $missingCritical += $dll
            }
          }
          
          if ($missingCritical.Count -gt 0) {
            Write-Error "Critical DLLs missing: $($missingCritical -join ', ')"
            exit 1
          }
          
          # Create zip archive
          Compress-Archive -Path release-windows\* -DestinationPath codemap-windows-x64.zip
          Write-Host "Created release package: codemap-windows-x64.zip"
          
      - name: Test executable
        run: |
          cd release-windows
          Write-Host "Testing bundled executable..."
          .\codemap.exe --help
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Executable test failed"
            exit 1
          }
          Write-Host "Executable test passed!"
          
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codemap-windows-x64
          path: codemap-windows-x64.zip

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libclang-18-dev llvm-18-dev
          
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        
      - name: Build
        run: cmake --build build -j$(nproc)
        
      - name: Package Linux Release
        run: |
          mkdir -p release-linux/codemap-linux-x64
          cp build/bin/codemap release-linux/codemap-linux-x64/
          cp -r frontend release-linux/codemap-linux-x64/
          cp README.md release-linux/codemap-linux-x64/
          cd release-linux
          tar -czf ../codemap-linux-x64.tar.gz codemap-linux-x64
          cd ..
          
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codemap-linux-x64
          path: codemap-linux-x64.tar.gz

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: codemap-windows-x64
          
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: codemap-linux-x64
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            codemap-windows-x64.zip
            codemap-linux-x64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Download
            
            ### Windows x64 (Self-Contained)
            Download `codemap-windows-x64.zip` and extract. The package includes:
            - `codemap.exe` - Main executable
            - All required LLVM/libclang DLLs (bundled)
            - `frontend/` - Web visualization files
            - `bundle-manifest.txt` - List of bundled dependencies
            
            **No LLVM installation required!** Just extract and run:
            ```cmd
            codemap.exe --help
            codemap.exe C:\path\to\project
            ```
            
            Note: If you encounter any issues, ensure Visual C++ Redistributable is installed:
            https://aka.ms/vs/17/release/vc_redist.x64.exe
            
            ### Linux x64
            Download `codemap-linux-x64.tar.gz` and extract:
            ```bash
            tar -xzf codemap-linux-x64.tar.gz
            cd codemap-linux-x64
            ./codemap --help
            ```